name: Uggi
favicon: null
layout_spectrum: 0.6333649819716811
typography_spectrum: 0.645429365336895
title: Uggi lights. Lamps made from fish skin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#ffffff'
    - '#4b4b4b'
    - '#8d8d8d'
    - '#bfbfbf'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
